export const ImageInfo = [
    [require("./../img/0.jpg"), "Bald darfst du wieder an ferne Orte fliegen!"],
    [require("./../img/1.jpg"), "Auf zum Festival mit deinen Freunden!"],
    [require("./../img/2.jpg"), "Endlich wieder unendliches Shoppen!"],
    [require("./../img/3.jpg"), "Auch ferne Inseln bereisen ist bald kein Problem mehr!"],
    [require("./../img/4.jpg"), "Endlich wieder (lecker) essen gehen!"],
    [require("./../img/5.jpg"), "Bald wieder richtig feiern gehen!"],
    [require("./../img/6.jpg"), "Ferne Strände warten auf dich!"],
    [require("./../img/7.jpg"), "Auch die Kultur lebt wieder auf!"],
    [require("./../img/8.jpg"), "Auf in das Gassengewirr der Altstadt!"],
    [require("./../img/9.jpg"), "\"Komm, steig' ein!\""],
    [require("./../img/10.jpg"), "Wie wär's mit griechischer Küche?"],
    [require("./../img/11.jpg"), "Auf zum Großstadt-Entdecken!"],
    [require("./../img/12.jpg"), "Raus aus der Einsiedlerhöhle!"],
    [require("./../img/13.jpg"), "Sommer, Sonne, Kaktus... und zwar nicht an der Nordsee!"],
    [require("./../img/14.jpg"), "Bald keine Abstandsregeln mehr!"],
    [require("./../img/15.jpg"), "Ferne Sonnenuntergänge erleben..."],
    [require("./../img/16.jpg"), "Endlich wieder auf große Messen gehen!"],
    [require("./../img/17.jpg"), "Vielleicht ein Tauchgang in der Südsee?"],
    [require("./../img/18.jpg"), "Bald wieder in's Restaurant ohne Einschränkungen!"],
    [require("./../img/19.jpg"), "Einfach wieder einen Urlaub buchen!"],
    [require("./../img/20.jpg"), "Ohne Maske auf's Konzert!"],
    [require("./../img/21.jpg"), "Dein verdienter Urlaub kommt!"],
    [require("./../img/22.jpg"), "Sight-Seeing? Kein Problem!"],
    [require("./../img/23.jpg"), "Mehr Reise-Souvenire sammeln!"],
    [require("./../img/24.jpg"), "Wieder frei wie ein Vogel sein!"],
    [require("./../img/25.jpg"), "Eine verrückte Städtetour durch Dänemark gefällig?"],
    [require("./../img/26.jpg"), "Endlich wieder Postkartenmotive in echt erleben!"],
    [require("./../img/27.jpg"), "Bald bist du nicht mehr allein!"],
    [require("./../img/28.jpg"), "Last-Minute an den Strand? Bald wieder möglich!"],
    [require("./../img/29.jpg"), "Einfach wieder an's Mittelmeer!"],
    [require("./../img/30.jpg"), "Bald wieder entspannt ohne Maske fliegen!"],
    [require("./../img/31.jpg"), "Bizarre Küstenlandschaften entdecken (also bald wieder)!"]
];